default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres

development:
  <<: *default
  database: redux_demo_development
test:
  <<: *default
  database: redux_demo_test

production:
  <<: *default
  database: redux_demo_production
  username: postgres
  password: postgres
